/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.adm.view;

import com.br.adm.dao.UsuarioDAO;
import com.br.adm.model.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dacru
 */
public class FormListFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form FormListFuncionarios
     */
   
    public FormListFuncionarios() {
        initComponents();
        listar();
    }
    
    public void listar() {
    try {
        UsuarioDAO dao = new UsuarioDAO();
        List<Usuario> lista = dao.Listar();
        DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        
        for (Usuario c : lista) {
            dados.addRow(new Object[]{
                c.getId_usuario(),
                c.getNome(),
                c.getCpf(),
                c.getEmail(),
                c.getCd_nivelAcesso(),
                c.getSenha(),
                c.getCelular(),
                c.getTelefone(),
                c.getRua(),
                c.getNumero(),
                c.getBairro(),
                c.getCep()
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"O Erro:  " + e);
    }
}


    /*
         public void listar () {
            UsuarioDAO dao = new UsuarioDAO();
    List<Usuario> lista = dao.Listar();
           DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
           dados.setNumRows(0);
           for ( Usuario c : lista ) {
               dados.addRow(new Object[]{
                   c.getId_usuario(),
                   c.getNome(),
                   c.getCpf(),
                   c.getEmail(),
                   c.getCd_nivelAcesso(),
                   c.getSenha(),
                   c.getCelular(),
                   c.getTelefone(),
                   c.getRua(),
                   c.getNumero(),
                   c.getBairro(),
                   c.getCep()                 
             });
     }
           
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        superior = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lista de Usuários");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 150, 60));

        superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/adm/imagens/telas/listCopy.png"))); // NOI18N
        getContentPane().add(superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 556, 1200, 120));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "E-mail", "Nível de Acesso", "Senha", "Celular", "Telefone", "Rua", "Número", "Bairro", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setAutoscrolls(false);
        tabela.setCellSelectionEnabled(true);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
            tabela.getColumnModel().getColumn(5).setResizable(false);
            tabela.getColumnModel().getColumn(6).setResizable(false);
            tabela.getColumnModel().getColumn(7).setResizable(false);
            tabela.getColumnModel().getColumn(8).setResizable(false);
            tabela.getColumnModel().getColumn(9).setResizable(false);
            tabela.getColumnModel().getColumn(10).setResizable(false);
            tabela.getColumnModel().getColumn(11).setResizable(false);
        }
        // Tornando a tabela transparente
        tabela.setOpaque(false);
        tabela.setShowGrid(false);
        tabela.setBackground(new Color(0, 0, 0, 0)); // Fundo da tabela transparente
        ((DefaultTableCellRenderer) tabela.getTableHeader().getDefaultRenderer()).setOpaque(false);

        // Criando um renderizador para personalizar o fundo da célula
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (value != null && !value.toString().trim().isEmpty()) {
                    // Se a célula contém dados, aplica fundo cinza claro [240, 240, 240]
                    label.setOpaque(true);
                    label.setBackground(new Color(240, 240, 240));
                } else {
                    // Se a célula estiver vazia, deixa o fundo transparente
                    label.setOpaque(false);
                }

                return label;
            }
        };

        // Aplicando o renderizador personalizado às colunas
        for (int i = 0; i < tabela.getColumnCount(); i++) {
            tabela.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        // Ajustando a transparência no JScrollPane se a tabela estiver dentro de um
        if (tabela.getParent() instanceof JViewport) {
            JViewport viewport = (JViewport) tabela.getParent();
            viewport.setOpaque(false);
            if (viewport.getParent() instanceof JScrollPane) {
                JScrollPane scrollPane = (JScrollPane) viewport.getParent();
                scrollPane.setOpaque(false);
                scrollPane.getViewport().setOpaque(false);
                scrollPane.setBorder(null);
            }
        }

        // Configurações extras para evitar linhas visíveis nas células vazias
        tabela.setFillsViewportHeight(true);
        tabela.setIntercellSpacing(new Dimension(0, 0));

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 1200, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/adm/imagens/telas/list.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new FormCadrastoFuncionarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        FormCadrastoFuncionarios f = new FormCadrastoFuncionarios();
        //Verifica se a posição possui conteudo.
        int linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
        f.setVisible(true);
        this.setVisible(false);
        f.txtID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        f.txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        f.txtCpf.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        f.txtEmail.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        f.cb_nivel_acesso.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        f.txtSenha.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        f.txtCelular.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        f.txtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
        f.txtRua.setText(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
        f.txtNumero.setText(tabela.getValueAt(tabela.getSelectedRow(), 9).toString());
        f.txtBairro.setText(tabela.getValueAt(tabela.getSelectedRow(), 10).toString());
        f.txtCep.setText(tabela.getValueAt(tabela.getSelectedRow(), 11).toString());
        }
    }//GEN-LAST:event_tabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel superior;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
