/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.adm.view;

import com.br.adm.dao.UsuarioDAO;
import com.br.adm.model.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dacru
 */
public class FormListFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form FormListFuncionarios
     */
   
    public FormListFuncionarios() {
        initComponents();
        listar();
    }
    
    public void listar() {
    try {
        UsuarioDAO dao = new UsuarioDAO();
        List<Usuario> lista = dao.Listar();
        DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        
        for (Usuario c : lista) {
            dados.addRow(new Object[]{
                c.getId_usuario(),
                c.getNome(),
                c.getCpf(),
                c.getEmail(),
                c.getCd_nivelAcesso(),
                c.getSenha(),
                c.getCelular(),
                c.getTelefone(),
                c.getRua(),
                c.getNumero(),
                c.getBairro(),
                c.getCep()
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"O Erro:  " + e);
    }
}


    /*
         public void listar () {
            UsuarioDAO dao = new UsuarioDAO();
    List<Usuario> lista = dao.Listar();
           DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
           dados.setNumRows(0);
           for ( Usuario c : lista ) {
               dados.addRow(new Object[]{
                   c.getId_usuario(),
                   c.getNome(),
                   c.getCpf(),
                   c.getEmail(),
                   c.getCd_nivelAcesso(),
                   c.getSenha(),
                   c.getCelular(),
                   c.getTelefone(),
                   c.getRua(),
                   c.getNumero(),
                   c.getBairro(),
                   c.getCep()                 
             });
     }
           
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lista de Usuários");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "E-mail", "Nivel", "Senha", "Celular", "Telefone", "Rua", "Nº", "Bairro", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setAutoscrolls(false);
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1200, 220));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/adm/imagens/telas/list.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        FormCadrastoFuncionarios f = new FormCadrastoFuncionarios();        
        f.setVisible(true);
        f.txtID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        f.txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        f.txtCpf.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        f.txtEmail.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        f.cb_nivel_acesso.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        f.txtSenha.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        f.txtCelular.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        f.txtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
        f.txtRua.setText(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
        f.txtNumero.setText(tabela.getValueAt(tabela.getSelectedRow(), 9).toString());
        f.txtBairro.setText(tabela.getValueAt(tabela.getSelectedRow(), 10).toString());
        f.txtCep.setText(tabela.getValueAt(tabela.getSelectedRow(), 11).toString());
        this.setVisible(false);        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new FormCadrastoFuncionarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
